### PR TITLE
added bower.json

### PR DESCRIPTION
**Pull request by benjiwheeler**
unsure about main being transform-all.js ... currently ignoring (meaning, bower doesn't fetch these files from github) everything but lib/ and doc files

### CODE REVIEW

**Comment by bjouhier** [comment]
There are two files for browser-side scenarios: 

* `transform-all.js` if you intend to load the `*._js` files and transform them in the browser
* `runtime-all.js` if you load files that have already been transformed on the server side and if you only need the runtime in the browser. 

You should load one of these two files.

There are two variants of these files: a `callbacks` variant that runs on all browsers and a `generators` variant that only runs on recent browsers.

I don't know if you need to change the bower.json file. Let me know when you are ready and I'll merge the PR.

**Comment by benjiwheeler** [comment]
i added runtime-all and submitted a new PR: https://github.com/Sage/streamlinejs/pull/269

**Comment by bjouhier** [comment]
I merged the other PR. 

BTW you can add commits to an existing PR. If you commit them in your branch and push to your fork they are automatically added to the PR.

**Comment by benjiwheeler** [comment]
thanks! some maintainers like PRs to consist of just one commit, so as not
to pollute the commit history... and (i think) once i've pushed to my repo
and submitted the PR, i can't rebase further commits onto that one, right?

-Ben

--------------------
Ben Wheeler
mobile 917.254.1578
latest project: dailydayo.com
personal site: techno-social.com

**Comment by bjouhier** [comment]
I don't mind if a PR has several commits (but not too many).

The key to manage PRs is to create a feature branch. If you push a branch and create the PR from the branch you can add commits to your branch later and they will automatically land in the PR when you push. I like this better because it keeps all the changes into a single PR until the PR gets accepted.

**Pull request closed without merging**
